version: "3.7"
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - SA_PASSWORD=ownerTest1234
      - ACCEPT_EULA=Y
    ports:
      - target: 1433
        published: 1433
        protocol: tcp
        mode: host
